# Generated by Django 3.2.4 on 2022-02-06 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecturer',
            new_name='Parent',
        ),
    ]
