# Generated by Django 3.2.13 on 2022-09-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_lecturer_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name_plural': 'Parent'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
    ]
